language: python
python:
  - "3.8"
before_install: 
  - export TZ='Asia/Shanghai'
  - git config --global user.name "jckling"
  - git config --global user.email "jckling@163.com"
install:
  - pip install -r requirements.txt
script:
  - python update_readme.py
after_script:
  - git diff
  - git add -A
  - git commit -m "Update README.md"
  - git push "https://${GH_TOKEN}@github.com/jckling/jckling.git" master:master