name: Update Profile

on:
  push:
  schedule:
    - cron: '45 23 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Echo current time
        run: timedatectl

      - name: Git config
        run: |
          git config --global user.name "jckling"
          git config --global user.email "jckling@163.com"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Update README
        run: python update_readme.py

      - name: Deploy changes
        run: |
          if ! git diff --exit-code; then
            git add .
            git commit -m "Github Action Automated Update $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
