name: Update Profile

on:
  push:
  schedule:
    - cron: '45 23 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Echo current time
        run: timedatectl

      - name: Git config
        run: |
          git config --global user.name "jckling"
          git config --global user.email "jckling@163.com"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Update README
        run: python update_readme.py
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        
      - name: Deploy changes
        if: contains(steps.changed-files.outputs.modified_files, 'README.md')
        run: |
          git add .
          git commit -m "Github Action Automated Update $(date +'%Y-%m-%d %H:%M:%S')"
          git push
