name: Update Profile

on:
  push:
  schedule:
    - cron: '45 23 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Set up timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Echo current time
        run: timedatectl

      - name: Git config
        run: |
          git config --global user.name "jckling"
          git config --global user.email "jckling@163.com"

      - name: Update README
        run: uv run update.py

      - name: Deploy changes
        run: |
          if ! git diff --exit-code; then
            git add .
            git commit -m "Github Action Automated Update $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
